### ISSUE TITLE
question about FaceAlignment's prototxt

### ISSUE THREAD

**Issue by peternara** [RiweiChen/DeepFace#1]
hi. i see your code about FaceAlignment
i wonder elements about FaceAlignment's prototxt
(i have a error duration training)
this prototxt...(train_val.prototxt)

layers {
  name: "conv2"
  type: **LOCAL**
  bottom: "pool1"
  top: "conv2"
  blobs_lr: 1
  blobs_lr: 2
  **local_param** {
    num_output: 40
    kernel_size: 3
    stride: 1
    #pad: 2
    weight_filler {
      type: "xavier"
    }
    bias_filler {
      type: "constant"
      value: 0.1
    }
  }
}
## 

error : LOCAL & local_param

caffe not understand this elements.

how to ...??

**Comment by chenriwei** [comment]
Hi @peternara, the Local Layer is from [caffe-local](https://github.com/jackculpepper/caffe/tree/local), you should checkout this caffe version.
