### ISSUE TITLE
请教lfw的测试方法

### ISSUE THREAD

**Issue by Jason-Zhou-JC** [RiweiChen/DeepFace#13]
你好，我最近在测试lfw的准确率，但不是很了解，有看官网，对测试不是很确定。它的测试数据分为10个文件夹，是不是每次以9个为训练集，另一个为验证集。然后对这10个文件循环一次做训练集和验证集，这样对吗？最后的结果以10次准确率的平均为结果，是不是？

**Comment by chenriwei** [comment]
Hi， @Jason-Zhou-JC LFW测试分为训练集和验证集合，一般用DL去做的话，会采用大量的外部数据，所以，这个训练集合其实是没有什么用的，所以只用验证集合，验证集合中，分为10分，我的做法：每一份分别测试ROC曲线和精度，然后计算均值和方差，因为没有提交过lfw效果，所以也不敢确定这样有没有问题。
