### ISSUE TITLE
no layer names 'LOCAL'

### ISSUE THREAD

**Issue by twinsyssy1018** [RiweiChen/DeepFace#14]
hi, i used the deploy.prototxt file to do face point detection, but the conv layer was named as 'LOCAL',which is not a name in Caffe. so i tried to use 'type: CONVOLUTION' instead, but the model you provided can not work , here is the error message:
 Cannot copy param 0 weights from layer 'conv1'; shape mismatch. 

i think my Caffe is different with yours .  could you provide your caffe too? thank you

**Comment by chenriwei** [comment]
hi, you can use the version of caffe in [here](https://github.com/RiweiChen/DeepFace/tree/master/resource)
