### ISSUE TITLE
train_2.list, val_2.list ?

### ISSUE THREAD

**Issue by saladin0786** [RiweiChen/DeepFace#15]
Hi, I was looking 'FaceDetection''s train_val.prototxt of try2_1, but I couldn't find those file.

How can I get train_2.list & val_2.list ?  Thx

**Comment by chenriwei** [comment]
hi, @James0786 , you can generate the file by yourself,  you can reference the follow code. [see](https://github.com/RiweiChen/DeepFace/blob/master/util/div_train_val.py)
