### ISSUE TITLE
fully-convolution layer settings

### ISSUE THREAD

**Issue by KissyZhou** [RiweiChen/DeepFace#23]
hi,
    why the transformed model, named deploy_fc.prototxt, set the 'deepid-conv' layer to be 'num_output :160    kernel_size : 1' ?
    according to [this](http://nbviewer.jupyter.org/github/BVLC/caffe/blob/master/examples/net_surgery.ipynb), i think  the kernel size in 'deepid-conv'  layer should be 3. cause the output size of 'pool4' layer is 80x3x3 and the parameter size of 'deepid' layer is 160 \* 720(115200), however parameter size in the 'deepid-conv' layer is 160 x 80 x 1 x 1 (12800 not equal to 115200)...  any suggestions about this?? 
    thx in advance.

**Comment by chenriwei** [comment]
hi, @KissyZhou, IMO, we should only care the full-connect layer itself, as you know, full-connect layer can be seen as a convolution layer , which  kernel_size be 1.

**Comment by kli-casia** [comment]
同意 @KissyZhou 的说法，第一个全连接层改成conv层kernel大小应该是3x3，而第二个全连接层改成conv层kernel大小是1x1
