### ISSUE TITLE
loading model problem

### ISSUE THREAD

**Issue by mohamad-hasan-sohan-ajini** [RiweiChen/DeepFace#26]
Hi

I try to load face alignment model but get the the following error:

> WARNING: Logging before InitGoogleLogging() is written to STDERR
W1225 16:07:29.089817 26911 _caffe.cpp:122] DEPRECATION WARNING - deprecated use of Python interface
W1225 16:07:29.089855 26911 _caffe.cpp:123] Use this instead (with the named "weights" parameter):
W1225 16:07:29.089861 26911 _caffe.cpp:125] Net('../try1_2/depoly.prototxt', 1, weights='../Model/try1_2/snapshot_iter_1500000.caffemodel')
[libprotobuf ERROR google/protobuf/text_format.cc:245] Error parsing text-format caffe.NetParameter: 10:3: Unknown enumeration value of "LOCAL" for field "type".
F1225 16:07:29.091105 26911 upgrade_proto.cpp:88] Check failed: ReadProtoFromTextFile(param_file, param) Failed to parse NetParameter file: ../try1_2/depoly.prototxt
*** Check failure stack trace: ***
Aborted (core dumped)

where is the problem?

**Comment by Grauen** [comment]
`DEPRECATION WARNING`

`Error parsing text-format caffe.NetParameter: 10:3: Unknown enumeration value of "LOCAL" for field "type".`

Check out this issue
https://github.com/torrvision/crfasrnn/issues/45

Looks like your version of caffe is not compatible with deepface.
