### ISSUE TITLE
询问lfw的测试精度情况

### ISSUE THREAD

**Issue by dlyshare** [RiweiChen/DeepFace#3]
请问用您这个模型在lfw上实测, 精度能达到多少呢?

**Comment by chenriwei** [comment]
@dlyshare ，基础的DeepID网络结构，模型大概只有84%左右，我自己没有开源的模型可以达到98%左右

**Comment by getengqing** [comment]
hello,Chen!没有开源的98%左右模型可不可以开源下，参考参考？
