### ISSUE TITLE
LMDB for custom image dataset for Face recognition using Caffe

### ISSUE THREAD

**Issue by PiyalGeorge** [RiweiChen/DeepFace#36]
Hi, I'm new to Caffe. I have done the face detection using caffe. Now i'm trying to perform face recognition using Caffe, using custom image dataset. The problem is i dont know where to start. Only thing i have is images of faces of several people. I know that we need to convert them to LMDB. Incase of Face Detection we give faces(without bothering about the people). But i dont know how to deal with several faces. Just help me

**Comment by ysh329** [comment]
same issue
