### ISSUE TITLE
error

### ISSUE THREAD

**Issue by punkhooren** [RiweiChen/DeepFace#4]
ren@keegan  /home/ren/Code/CaffeFace/DeepFace-master/FaceDetection/baseline   python evaluate_48.py
WARNING: Logging before InitGoogleLogging() is written to STDERR
I0308 10:43:48.193229  6102 net.cpp:42] Initializing net from parameters: 
name: "DeepID_face_detection"
input: "data"
input_dim: 1
input_dim: 3
input_dim: 2400
input_dim: 2400
state {
  phase: TEST
}
layer {
  name: "conv1"
  type: "Convolution"
  bottom: "data"
  top: "conv1"
  param {
    name: "conv1_w"
    lr_mult: 1
    decay_mult: 1
  }
  param {
    name: "conv1_b"
    lr_mult: 2
    decay_mult: 0
  }
  convolution_param {
    num_output: 20
    pad: 1
    kernel_size: 3
    stride: 1
    weight_filler {
      type: "gaussian"
      std: 0.01
    }
    bias_filler {
      type: "constant"
      value: 0
    }
  }
}
layer {
  name: "relu1"
  type: "ReLU"
  bottom: "conv1"
  top: "conv1"
}
layer {
  name: "norm1"
  type: "LRN"
  bottom: "conv1"
  top: "norm1"
  lrn_param {
    local_size: 5
    alpha: 0.0001
    beta: 0.75
  }
}
layer {
  name: "pool1"
  type: "Pooling"
  bottom: "norm1"
  top: "pool1"
  pooling_param {
    pool: MAX
    kernel_size: 2
    stride: 2
  }
}
layer {
  name: "conv2"
  type: "Convolution"
  bottom: "pool1"
  top: "conv2"
  param {
    name: "conv2_w"
    lr_mult: 1
    decay_mult: 1
  }
  param {
    name: "conv2_b"
    lr_mult: 2
    decay_mult: 0
  }
  convolution_param {
    num_output: 40
    pad: 1
    kernel_size: 3
    weight_filler {
      type: "gaussian"
      std: 0.01
    }
    bias_filler {
      type: "constant"
      value: 0.1
    }
  }
}
layer {
  name: "relu2"
  type: "ReLU"
  bottom: "conv2"
  top: "conv2"
}
layer {
  name: "norm2"
  type: "LRN"
  bottom: "conv2"
  top: "norm2"
  lrn_param {
    local_size: 5
    alpha: 0.0001
    beta: 0.75
  }
}
layer {
  name: "pool2"
  type: "Pooling"
  bottom: "norm2"
  top: "pool2"
  pooling_param {
    pool: MAX
    kernel_size: 2
    stride: 2
  }
}
layer {
  name: "conv3"
  type: "Convolution"
  bottom: "pool2"
  top: "conv3"
  param {
    name: "conv3_w"
    lr_mult: 1
    decay_mult: 1
  }
  param {
    name: "conv3_b"
    lr_mult: 2
    decay_mult: 0
  }
  convolution_param {
    num_output: 60
    pad: 1
    kernel_size: 3
    weight_filler {
      type: "gaussian"
      std: 0.01
    }
    bias_filler {
      type: "constant"
      value: 0.1
    }
  }
}
layer {
  name: "relu3"
  type: "ReLU"
  bottom: "conv3"
  top: "conv3"
}
layer {
  name: "norm3"
  type: "LRN"
  bottom: "conv3"
  top: "norm3"
  lrn_param {
    local_size: 5
    alpha: 0.0001
    beta: 0.75
  }
}
layer {
  name: "pool3"
  type: "Pooling"
  bottom: "norm3"
  top: "pool3"
  pooling_param {
    pool: MAX
    kernel_size: 2
    stride: 2
  }
}
layer {
  name: "conv4"
  type: "Convolution"
  bottom: "pool3"
  top: "conv4"
  param {
    name: "conv4_w"
    lr_mult: 1
    decay_mult: 1
  }
  param {
    name: "conv4_b"
    lr_mult: 2
    decay_mult: 0
  }
  convolution_param {
    num_output: 80
    pad: 1
    kernel_size: 3
    weight_filler {
      type: "gaussian"
      std: 0.01
    }
    bias_filler {
      type: "constant"
      value: 0.1
    }
  }
}
layer {
  name: "relu4"
  type: "ReLU"
  bottom: "conv4"
  top: "conv4"
}
layer {
  name: "norm4"
  type: "LRN"
  bottom: "conv4"
  top: "norm4"
  lrn_param {
    local_size: 5
    alpha: 0.0001
    beta: 0.75
  }
}
layer {
  name: "pool4"
  type: "Pooling"
  bottom: "norm4"
  top: "pool4"
  pooling_param {
    pool: MAX
    kernel_size: 2
    stride: 2
  }
}
layer {
  name: "deepid-conv"
  type: "Convolution"
  bottom: "pool4"
  top: "deepid-conv"
  convolution_param {
    num_output: 160
    kernel_size: 1
  }
}
layer {
  name: "relu6"
  type: "ReLU"
  bottom: "deepid-conv"
  top: "deepid-conv"
}
layer {
  name: "fc7-conv"
  type: "Convolution"
  bottom: "deepid-conv"
  top: "fc7-conv"
  convolution_param {
    num_output: 2
    kernel_size: 1
  }
}
layer {
  name: "prob"
  type: "Softmax"
  bottom: "fc7-conv"
  top: "prob"
}
I0308 10:43:48.193851  6102 net.cpp:370] Input 0 -> data
I0308 10:43:48.202942  6102 layer_factory.hpp:74] Creating layer conv1
I0308 10:43:48.203001  6102 net.cpp:90] Creating Layer conv1
I0308 10:43:48.203017  6102 net.cpp:410] conv1 <- data
I0308 10:43:48.203035  6102 net.cpp:368] conv1 -> conv1
I0308 10:43:48.203055  6102 net.cpp:120] Setting up conv1
I0308 10:43:50.349145  6102 net.cpp:127] Top shape: 1 20 2400 2400 (115200000)
I0308 10:43:50.349195  6102 layer_factory.hpp:74] Creating layer relu1
I0308 10:43:50.349208  6102 net.cpp:90] Creating Layer relu1
I0308 10:43:50.349215  6102 net.cpp:410] relu1 <- conv1
I0308 10:43:50.349221  6102 net.cpp:357] relu1 -> conv1 (in-place)
I0308 10:43:50.349231  6102 net.cpp:120] Setting up relu1
I0308 10:43:50.349428  6102 net.cpp:127] Top shape: 1 20 2400 2400 (115200000)
I0308 10:43:50.349447  6102 layer_factory.hpp:74] Creating layer norm1
I0308 10:43:50.349458  6102 net.cpp:90] Creating Layer norm1
I0308 10:43:50.349463  6102 net.cpp:410] norm1 <- conv1
I0308 10:43:50.349469  6102 net.cpp:368] norm1 -> norm1
I0308 10:43:50.349478  6102 net.cpp:120] Setting up norm1
I0308 10:43:50.349488  6102 net.cpp:127] Top shape: 1 20 2400 2400 (115200000)
I0308 10:43:50.349493  6102 layer_factory.hpp:74] Creating layer pool1
I0308 10:43:50.349501  6102 net.cpp:90] Creating Layer pool1
I0308 10:43:50.349506  6102 net.cpp:410] pool1 <- norm1
I0308 10:43:50.349512  6102 net.cpp:368] pool1 -> pool1
I0308 10:43:50.349519  6102 net.cpp:120] Setting up pool1
I0308 10:43:50.365315  6102 net.cpp:127] Top shape: 1 20 1200 1200 (28800000)
I0308 10:43:50.365340  6102 layer_factory.hpp:74] Creating layer conv2
I0308 10:43:50.365358  6102 net.cpp:90] Creating Layer conv2
I0308 10:43:50.365365  6102 net.cpp:410] conv2 <- pool1
I0308 10:43:50.365375  6102 net.cpp:368] conv2 -> conv2
I0308 10:43:50.365389  6102 net.cpp:120] Setting up conv2
I0308 10:43:50.367513  6102 net.cpp:127] Top shape: 1 40 1200 1200 (57600000)
I0308 10:43:50.367563  6102 layer_factory.hpp:74] Creating layer relu2
I0308 10:43:50.367576  6102 net.cpp:90] Creating Layer relu2
I0308 10:43:50.367583  6102 net.cpp:410] relu2 <- conv2
I0308 10:43:50.367588  6102 net.cpp:357] relu2 -> conv2 (in-place)
I0308 10:43:50.367596  6102 net.cpp:120] Setting up relu2
I0308 10:43:50.367911  6102 net.cpp:127] Top shape: 1 40 1200 1200 (57600000)
I0308 10:43:50.367933  6102 layer_factory.hpp:74] Creating layer norm2
I0308 10:43:50.367943  6102 net.cpp:90] Creating Layer norm2
I0308 10:43:50.367949  6102 net.cpp:410] norm2 <- conv2
I0308 10:43:50.367955  6102 net.cpp:368] norm2 -> norm2
I0308 10:43:50.367964  6102 net.cpp:120] Setting up norm2
I0308 10:43:50.367975  6102 net.cpp:127] Top shape: 1 40 1200 1200 (57600000)
I0308 10:43:50.367980  6102 layer_factory.hpp:74] Creating layer pool2
I0308 10:43:50.367987  6102 net.cpp:90] Creating Layer pool2
I0308 10:43:50.367992  6102 net.cpp:410] pool2 <- norm2
I0308 10:43:50.367998  6102 net.cpp:368] pool2 -> pool2
I0308 10:43:50.368005  6102 net.cpp:120] Setting up pool2
I0308 10:43:50.368131  6102 net.cpp:127] Top shape: 1 40 600 600 (14400000)
I0308 10:43:50.368140  6102 layer_factory.hpp:74] Creating layer conv3
I0308 10:43:50.368161  6102 net.cpp:90] Creating Layer conv3
I0308 10:43:50.368166  6102 net.cpp:410] conv3 <- pool2
I0308 10:43:50.368173  6102 net.cpp:368] conv3 -> conv3
I0308 10:43:50.368185  6102 net.cpp:120] Setting up conv3
I0308 10:43:50.370653  6102 net.cpp:127] Top shape: 1 60 600 600 (21600000)
I0308 10:43:50.370688  6102 layer_factory.hpp:74] Creating layer relu3
I0308 10:43:50.370707  6102 net.cpp:90] Creating Layer relu3
I0308 10:43:50.370717  6102 net.cpp:410] relu3 <- conv3
I0308 10:43:50.370728  6102 net.cpp:357] relu3 -> conv3 (in-place)
I0308 10:43:50.370741  6102 net.cpp:120] Setting up relu3
I0308 10:43:50.371130  6102 net.cpp:127] Top shape: 1 60 600 600 (21600000)
I0308 10:43:50.371153  6102 layer_factory.hpp:74] Creating layer norm3
I0308 10:43:50.371170  6102 net.cpp:90] Creating Layer norm3
I0308 10:43:50.371179  6102 net.cpp:410] norm3 <- conv3
I0308 10:43:50.371191  6102 net.cpp:368] norm3 -> norm3
I0308 10:43:50.371207  6102 net.cpp:120] Setting up norm3
I0308 10:43:50.371232  6102 net.cpp:127] Top shape: 1 60 600 600 (21600000)
I0308 10:43:50.371242  6102 layer_factory.hpp:74] Creating layer pool3
I0308 10:43:50.371254  6102 net.cpp:90] Creating Layer pool3
I0308 10:43:50.371263  6102 net.cpp:410] pool3 <- norm3
I0308 10:43:50.371274  6102 net.cpp:368] pool3 -> pool3
I0308 10:43:50.371286  6102 net.cpp:120] Setting up pool3
I0308 10:43:50.371572  6102 net.cpp:127] Top shape: 1 60 300 300 (5400000)
I0308 10:43:50.371592  6102 layer_factory.hpp:74] Creating layer conv4
I0308 10:43:50.371608  6102 net.cpp:90] Creating Layer conv4
I0308 10:43:50.371618  6102 net.cpp:410] conv4 <- pool3
I0308 10:43:50.371631  6102 net.cpp:368] conv4 -> conv4
I0308 10:43:50.371646  6102 net.cpp:120] Setting up conv4
I0308 10:43:50.374976  6102 net.cpp:127] Top shape: 1 80 300 300 (7200000)
I0308 10:43:50.375010  6102 layer_factory.hpp:74] Creating layer relu4
I0308 10:43:50.375026  6102 net.cpp:90] Creating Layer relu4
I0308 10:43:50.375036  6102 net.cpp:410] relu4 <- conv4
I0308 10:43:50.375048  6102 net.cpp:357] relu4 -> conv4 (in-place)
I0308 10:43:50.375061  6102 net.cpp:120] Setting up relu4
I0308 10:43:50.375435  6102 net.cpp:127] Top shape: 1 80 300 300 (7200000)
I0308 10:43:50.375457  6102 layer_factory.hpp:74] Creating layer norm4
I0308 10:43:50.375471  6102 net.cpp:90] Creating Layer norm4
I0308 10:43:50.375480  6102 net.cpp:410] norm4 <- conv4
I0308 10:43:50.375495  6102 net.cpp:368] norm4 -> norm4
I0308 10:43:50.375509  6102 net.cpp:120] Setting up norm4
I0308 10:43:50.375522  6102 net.cpp:127] Top shape: 1 80 300 300 (7200000)
I0308 10:43:50.375532  6102 layer_factory.hpp:74] Creating layer pool4
I0308 10:43:50.375545  6102 net.cpp:90] Creating Layer pool4
I0308 10:43:50.375553  6102 net.cpp:410] pool4 <- norm4
I0308 10:43:50.375566  6102 net.cpp:368] pool4 -> pool4
I0308 10:43:50.375577  6102 net.cpp:120] Setting up pool4
I0308 10:43:50.375849  6102 net.cpp:127] Top shape: 1 80 150 150 (1800000)
I0308 10:43:50.375867  6102 layer_factory.hpp:74] Creating layer deepid-conv
I0308 10:43:50.375885  6102 net.cpp:90] Creating Layer deepid-conv
I0308 10:43:50.375895  6102 net.cpp:410] deepid-conv <- pool4
I0308 10:43:50.375907  6102 net.cpp:368] deepid-conv -> deepid-conv
I0308 10:43:50.375921  6102 net.cpp:120] Setting up deepid-conv
I0308 10:43:50.377126  6102 net.cpp:127] Top shape: 1 160 150 150 (3600000)
I0308 10:43:50.377161  6102 layer_factory.hpp:74] Creating layer relu6
I0308 10:43:50.377177  6102 net.cpp:90] Creating Layer relu6
I0308 10:43:50.377187  6102 net.cpp:410] relu6 <- deepid-conv
I0308 10:43:50.377199  6102 net.cpp:357] relu6 -> deepid-conv (in-place)
I0308 10:43:50.377212  6102 net.cpp:120] Setting up relu6
I0308 10:43:50.377583  6102 net.cpp:127] Top shape: 1 160 150 150 (3600000)
I0308 10:43:50.377604  6102 layer_factory.hpp:74] Creating layer fc7-conv
I0308 10:43:50.377619  6102 net.cpp:90] Creating Layer fc7-conv
I0308 10:43:50.377629  6102 net.cpp:410] fc7-conv <- deepid-conv
I0308 10:43:50.377640  6102 net.cpp:368] fc7-conv -> fc7-conv
I0308 10:43:50.377653  6102 net.cpp:120] Setting up fc7-conv
I0308 10:43:50.378639  6102 net.cpp:127] Top shape: 1 2 150 150 (45000)
I0308 10:43:50.378669  6102 layer_factory.hpp:74] Creating layer prob
I0308 10:43:50.378684  6102 net.cpp:90] Creating Layer prob
I0308 10:43:50.378696  6102 net.cpp:410] prob <- fc7-conv
I0308 10:43:50.378708  6102 net.cpp:368] prob -> prob
I0308 10:43:50.378720  6102 net.cpp:120] Setting up prob
I0308 10:43:50.379678  6102 net.cpp:127] Top shape: 1 2 150 150 (45000)
I0308 10:43:50.379701  6102 net.cpp:194] prob does not need backward computation.
I0308 10:43:50.379712  6102 net.cpp:194] fc7-conv does not need backward computation.
I0308 10:43:50.379721  6102 net.cpp:194] relu6 does not need backward computation.
I0308 10:43:50.379731  6102 net.cpp:194] deepid-conv does not need backward computation.
I0308 10:43:50.379740  6102 net.cpp:194] pool4 does not need backward computation.
I0308 10:43:50.379750  6102 net.cpp:194] norm4 does not need backward computation.
I0308 10:43:50.379758  6102 net.cpp:194] relu4 does not need backward computation.
I0308 10:43:50.379766  6102 net.cpp:194] conv4 does not need backward computation.
I0308 10:43:50.379777  6102 net.cpp:194] pool3 does not need backward computation.
I0308 10:43:50.379786  6102 net.cpp:194] norm3 does not need backward computation.
I0308 10:43:50.379796  6102 net.cpp:194] relu3 does not need backward computation.
I0308 10:43:50.379804  6102 net.cpp:194] conv3 does not need backward computation.
I0308 10:43:50.379815  6102 net.cpp:194] pool2 does not need backward computation.
I0308 10:43:50.379824  6102 net.cpp:194] norm2 does not need backward computation.
I0308 10:43:50.379833  6102 net.cpp:194] relu2 does not need backward computation.
I0308 10:43:50.379842  6102 net.cpp:194] conv2 does not need backward computation.
I0308 10:43:50.379853  6102 net.cpp:194] pool1 does not need backward computation.
I0308 10:43:50.379861  6102 net.cpp:194] norm1 does not need backward computation.
I0308 10:43:50.379869  6102 net.cpp:194] relu1 does not need backward computation.
I0308 10:43:50.379878  6102 net.cpp:194] conv1 does not need backward computation.
I0308 10:43:50.379886  6102 net.cpp:235] This network produces output prob
I0308 10:43:50.379911  6102 net.cpp:482] Collecting Learning Rate and Weight Decay.
I0308 10:43:50.379925  6102 net.cpp:247] Network initialization done.
I0308 10:43:50.379933  6102 net.cpp:248] Memory required for data: 2649960000
E0308 10:43:50.442247  6102 upgrade_proto.cpp:618] Attempting to upgrade input file specified using deprecated V1LayerParameter: /home/ren/Code/CaffeFace/DeepFace-master/FaceDetection/try1_4/deploy.prototxt
E0308 10:43:50.442294  6102 upgrade_proto.cpp:636] Input NetParameter to be upgraded already specifies 'layer' fields; these will be ignored for the upgrade.
E0308 10:43:50.442327  6102 upgrade_proto.cpp:623] Warning: had one or more problems upgrading V1LayerParameter (see above); continuing anyway.
I0308 10:43:50.442374  6102 net.cpp:42] Initializing net from parameters: 
name: "DeepID_face_detection"
input: "data"
input_dim: 1
input_dim: 1
input_dim: 32
input_dim: 32
state {
  phase: TEST
}
layer {
  name: "relu3"
  type: "ReLU"
  bottom: "pool3"
  top: "pool3"
}
layer {
  name: "relu4"
  type: "ReLU"
  bottom: "conv4"
  top: "conv4"
}
layer {
  name: "relu5"
  type: "ReLU"
  bottom: "conv5"
  top: "conv5"
}
F0308 10:43:50.442462  6102 insert_splits.cpp:35] Unknown blob input pool3 to layer 0
**\* Check failure stack trace: ***
[1]    6102 abort (core dumped)  python evaluate_48.py

**Comment by chenriwei** [comment]
Hi, @KeeganRen, please use the latest version of  project. In more detail, please use the deploy.prototxt  file on [FaceDetection/baseline/deploy.prototxt](https://github.com/RiweiChen/DeepFace/blob/master/FaceDetection/baseline/deploy.prototxt)
