### ISSUE TITLE
Testing on a single image

### ISSUE THREAD

**Issue by nitish11** [RiweiChen/DeepFace#5]
Can you briefly outline  how to test the code on a single image? 
Thanks in advance.

**Comment by chenriwei** [comment]
@nitish11 what task you want perform on a sigle image? recognition, alignment or detection ?

**Comment by nitish11** [comment]
@RiweiChen : I am also implementing DeepFace. For this purpose, I need FaceDetection and  FaceAlignment. Could you explain  how to get 6 initial fiducial points and from those points, how to perform Face Alignment?
