### ISSUE TITLE
DeepID 的训练图片尺寸

### ISSUE THREAD

**Issue by joyhuang9473** [RiweiChen/DeepFace#6]
RiweiChen 你好，

在train_val.prototxt 的data layer 里有看你的训练图片尺寸为64x64，然而在[Deep Learning Face Representation from Predicting 10,000 Classes](http://www.ee.cuhk.edu.hk/~xgwang/papers/ sunWTcvpr14.pdf) (DeepID) 论文里提到港大使用的尺寸是39 × 31 或31 × 31

> The input is 39 × 31 × k for rectangle patches, and 31 × 31 × k for square patches, where k = 3 for color patches and k = 1 for gray patches.

想请问会选择用不同的尺寸大小是有什么样的考量吗？

谢谢！

**Comment by chenriwei** [comment]
你好，@joyhuang9473 其实没有严格的考量关系，只是说通常避免一个大的特征维度接到一个很小的特征维度中，只是我的个人经验而已。
