### ISSUE TITLE
about CelebA dataset

### ISSUE THREAD

**Issue by cheer37** [RiweiChen/DeepFace#7]
Hi, Do you have the identity information for CelebA dataset to use it for face recognition training?
If you have, please provide me.
Thanks in advance.

**Comment by chenriwei** [comment]
Hi, @cheer37 the attachment is namelist of the CelebA dataset.
[names.txt](https://github.com/RiweiChen/DeepFace/files/211037/names.txt)

**Comment by cheer37** [comment]
Hi sir.
This is the namelist for CASIA WebFace, not CelebA.
Please provide me with CelebA namelist.
Thanks.

**Comment by cheer37** [comment]
Hello? Are you there?

**Comment by chenriwei** [comment]
Hi, @cheer37 ,I am sorry of the misleading. I don't have the CelebA namelist either. I have try to contact the authors of the CelebA, they said in currently time, they has no plan to release the namelist data.

**Comment by cheer37** [comment]
Thank you anyway, RiweiChen.
