### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by Fatemeh89** [RiweiChen/DeepFace#8]
Dear Riwei Chen,

Why did you use different database in facedetection and face recognition?

Also you said that "For more implement details, please reference my blog"
- [1983的专栏](http://blog.csdn.net/chenriwei2)

May I ask put the direct link of your project on your blog, please? Because your blog is not English and I couldn't find the detail of your project in your blog.

**Comment by chenriwei** [comment]
Hi, @FSFHMSR, as face detection is independence with the face recognition, it doesn't have to share the same database (another problem is we don't have dataset that contain both identify and face bounding box label).

I will translate the blogs to github after I finish the current task.
