### ISSUE TITLE
Add new person

### ISSUE THREAD

**Issue by alisadra** [RiweiChen/DeepFace#9]
Dear Riwei Chen,
May I ask what happened when I want to add a new person into trained model? Shall I re-train all section of your NET or no need to re-train FaceDetection and FaceAlignment step?
So, Could you tell me how long does it take, please? Do you have any suggest for me if I want to add new person into existing class?

**Comment by chenriwei** [comment]
Hi @alisadra, I think you want  add a new person to a trained face recognition model? In the current implement, it have to re-train, but you can fine-tuning the trained models, it can be faster than re-train from scratch. maybe it will cost a day to retrain a face recognition model(I suppose).
The FaceDetection and FaceAlignment is independence with the FaceRecognition, you can use any other tools to processing the face images.

**Comment by alisadra** [comment]
Dear Riwei Chen,
Thank you so much. May I ask which way would you recommend if I want to add a new person to a trained face recognition model and it can be fast?If i use GPU instead of CPU, can i make it faster than use only CPU? 
What is your mean when you said "maybe it will cost a day to retrain a face recognition model"? Which system configuration you mean that?

**Comment by chenriwei** [comment]
hi @alisadra, in my opinion, you just used the trained model to extract feature, it make no sense if you only add one new person to retrain the face model(you should be clear that you want to perform face recognition(1:N) or face verification(1:1) ).

about "maybe it will cost a day to retrain a face recognition model", I mean when you add new person to training the network(fine-tuning the previous model but not from scratch), you maybe have to fine-tuning a day of time.
